<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE agenda [
<!ELEMENT agenda (contacto+)>
<!ELEMENT contacto(nombre, apellidos, direccion, telefonos)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT direccion (calle, numero, piso, cp, ciudad, provincia)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT piso (#PCDATA)>
<!ELEMENT cp (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT telefonos (tel)>
<!ELEMENT tel (#PCDATA)>
<!ATTLIST tel tipo CDATA #REQUIRED>
]>

<agenda>
    <contacto>
        <nombre>Manuel</nombre>
        <apellidos>Gomez Gomez</apellidos>
        <direccion>
            <calle>Geranio</calle>
            <numero>4</numero>
            <piso>1A</piso>
            <cp>21001</cp>
            <ciudad>Huelva</ciudad>
            <provincia>Huelva</provincia>
        </direccion>
        <telefonos>
            <tel tipo="casa">959100100</tel>
            <tel tipo="movil">600100100</tel>
            <tel tipo="trabajo">959200200<tel>
        </telefonos>
    </contacto>
</agenda>