<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE paises [
<!ELEMENT paises (pais, ciudad?)*>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>
]>
<paises>
    <pais>
        italia
        <ciudad>florencia</ciudad>
    </pais>
    <pais>
        portugal
        <ciudad>lisboa</ciudad>
        <ciudad>oporto</ciudad>
    </pais>
    <pais>francia</pais>
</paises>