<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE socios [
<!ELEMENT socios (socio)*>
<!ELEMENT socio ((numero, clave)+, nombre, edad)>
<!ELEMENT clave ANY>
<!ELEMENT edad ANY>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT numero ANY>
]>

<socios>
    <socio>
        <nombre>Ana</nombre>
        <edad>21</edad>
    </socio>
    <socio>
        <numero>598</numero>
        <nombre>Iker</nombre>
        <edad>19</edad>
    </socio>
    <socio>
        <clave>hY75Du</clave>
        <nombre>Iker</nombre>
    </socio>
</socios>