<!DOCTYPE formas [
<!ELEMENT formas (cuadrado, triangulo, circulo, otra)>
<!ELEMENT cuadrado (#PCDATA)>
<!ATTLIST cuadrado lados CDATA #REQUIRED>
<!ELEMENT triangulo (#PCDATA)>
<!ATTLIST triangulo lados CDATA #REQUIRED>
<!ELEMENT circulo (#PCDATA)>
<!ELEMENT otra EMPTY>
<!ATTLIST otra lados CDATA #REQUIRED>
]>

<formas>
    <cuadrado lados="4">tablero</cuadrado>
    <circulo>anilla</circulo>
    <triangulo>se√±al</triangulo>
    <circulo></circulo>
    <otra lados="7"/>
</formas>